[build]
builder = "NIXPACKS"
buildCommand = "chmod +x build.sh && ./build.sh"

[deploy]
startCommand = "gunicorn app:server"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[variables]
PYTHON_VERSION = "3.9.16"
